spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  kafka:
    consumer:
      bootstrap-servers: localhost:10000
    producer:
      bootstrap-servers: localhost:10000

logging:
  level:
    com.baedal: DEBUG

security:
  permit-all:
    urls: /api/**/login, /api/**/signup, /error, /swagger-ui/**, /v3/api-docs/**, /swagger-resources/**
