server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/owner
    username: owner
    password: owner
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  kafka:
    consumer:
      bootstrap-servers: localhost:10000
    producer:
      bootstrap-servers: localhost:10000